name: mkxp-z AArch64 Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ${{ secrets.DOCKER_IMAGE_PATH }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build Dependencies
        run: |
          cd linux
          # 도커 환경이 완벽하므로 그냥 make만 돌립니다.
          make -j$(nproc)

      - name: Main Build (mkxp-z)
        run: |
          # 이미 준비된 툴체인 파일로 메인 빌드만 수행
          meson setup build --cross-file /usr/local/share/aarch64-cross.txt --prefix=$GITHUB_WORKSPACE/dist
          ninja -C build install

      - name: Archive
        uses: actions/upload-artifact@v4
        with:
          name: mkxp-z-arm64
          path: dist/
